<?php
$paymentoption_followup_status = array ("10"=>"Payment Ok","1"=>"Payment Ok-Easy Payment","9"=>"Payment Ok-Online Payment","5"=>"Followup","2"=>"Customer Not Interested","4"=>"Phone Ringing - No Answer","3"=>"Wrong Phone No", "6"=>"Not Reachable", "7"=>"Already applied for Paid membership", "8"=>"Number Busy");
$leadsource = array(1=>"3D Secure Failure",2=>"Payment Failure",3=>"Payment Page Attempt",4=>"Phone",5=>"Email");
?>
