<html>
<head>
<title>Muslim Matrimonials, Muslim Matrimonial, Community Brides &amp; Grooms</title>
<meta name="description" content="MuslimMatrimony, Exclusive Matrimony Portal from MuslimMatrimony Click here to Register FREE &amp; get FREE Matches" />
<meta name="keywords" content="Muslim Matrimonial, Muslim Matrimonials, Muslim Matrimony" />
<meta name="Author" content="MuslimMatrimony.com Muslim Matrimonial Team" />
<meta name="copyright" content="Muslimmatrimony.com Matrimonials" />
<meta name="Distribution" content="general" />
  <link rel="stylesheet" href="http://img.muslimmatrimony.com/styles/landstyle.css" />
    <script language="javascript" src="http://img.muslimmatrimony.com/scripts/common.js"></script>
  <script language="javascript" src="http://img.muslimmatrimony.com/scripts/global.js"></script>
<script language="javascript" src="http://img.muslimmatrimony.com/scripts/landing1.js"></script>
 </HEAD>

 <BODY>
 <center>
<div id="maincontainer">
	<div id="container">
		<div class="padt5">
			<div class="fleft"><img src="http://img.muslimmatrimony.com/images/logo/muslim_logo.gif" width="380" height="40" alt="Muslim Matrimonials" border="0" vspace="10" /></div>
		</div>
		<div class="fleft lpanel1 tlleft padt7 padl10"><font class="headtxt clr4 bld">Find your lifepartner from your community</font></div>
		<div class="fleft rpanel1 tlleft"><div class="fleft"><img src="http://img.muslimmatrimony.com/images/regfree1.gif" /></div><div class="fleft padt12">&nbsp;&nbsp;&nbsp;<font class="smalltxt clr4">All fields are mandatory</font></div></div>
		<div class="fleft lpanel2" style="padding-top:2px;" id="musimgdiv">
			<a href="http://www.muslimmatrimony.com/register"><img src="http://img.muslimmatrimony.com/images/mus1.jpg" width="428" height="168" alt="Muslim Matrimony" border="0" /><br><img src="http://img.muslimmatrimony.com/images/mus2.jpg" width="428" height="168" alt="Muslim Matrimony" border="0" /></a>
		</div>
		<div class="fleft rpanel2">
			<center>
			<form name="landfrm" method="post" onSubmit="return validlandpage();">
			<input type="hidden" name="partnerLanding" value="yes" />
				<div style="width:310px;padding-top:20px;">
					<div class="ltform formtxt fleft">Name</div>
					<div class="rtform fleft"><input type="text" class="inputtext" name="name" /></div>
					<div class="ltform formtxt fleft">Age</div>
					<div class="rtform fleft"><select class="homeselect" style="width:40px;" name="dobMonth" onChange="document.landfrm.age.value='yrs';"><option value="0">MM</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option></select>
					<select class="homeselect" style="width:40px;" name="dobDay" onChange="document.landfrm.age.value='yrs';"><option selected="" value="0">DD</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option></select>
					<select class="homeselect" style="width:55px;" name="dobYear" onChange="document.landfrm.age.value='yrs';"><option value="0">YYYY</option><option value="1938">1938</option><option value="1939">1939</option><option value="1940">1940</option><option value="1941">1941</option><option value="1942">1942</option><option value="1943">1943</option><option value="1944">1944</option><option value="1945">1945</option><option value="1946">1946</option><option value="1947">1947</option><option value="1948">1948</option><option value="1949">1949</option><option value="1950">1950</option><option value="1951">1951</option><option value="1952">1952</option><option value="1953">1953</option><option value="1954">1954</option><option value="1955">1955</option><option value="1956">1956</option><option value="1957">1957</option><option value="1958">1958</option><option value="1959">1959</option><option value="1960">1960</option><option value="1961">1961</option><option value="1962">1962</option><option value="1963">1963</option><option value="1964">1964</option><option value="1965">1965</option><option value="1966">1966</option><option value="1967">1967</option><option value="1968">1968</option><option value="1969">1969</option><option value="1970">1970</option><option value="1971">1971</option><option value="1972">1972</option><option value="1973">1973</option><option value="1974">1974</option><option value="1975">1975</option><option value="1976">1976</option><option value="1977">1977</option><option value="1978">1978</option><option value="1979">1979</option><option value="1980">1980</option><option value="1981">1981</option><option value="1982">1982</option><option value="1983">1983</option><option value="1984">1984</option><option value="1985">1985</option><option value="1986">1986</option><option value="1987">1987</option><option value="1988">1988</option><option value="1989">1989</option><option value="1990">1990</option><option value="1991">1991</option></select> (or) <input type="text" class="inputtext" style="width:25px;" maxlength="2" value="yrs" name="age" onclick="javascript:this.select();" onBlur="if(document.landfrm.age.value!='yrs'){document.landfrm.dobMonth.value='0';document.landfrm.dobDay.value='0';document.landfrm.dobYear.value='0';}" /></div>
					<div class="ltform formtxt fleft">Gender</div>
					<div class="rtform fleft formtxt"><input id="gendermale" type="radio" value="1" name="gender" />Male&nbsp;&nbsp;&nbsp;<input type="radio" value="2" name="gender" />Female</div>
					<div id="selectdiv" style="display:none;">
					<div class="ltform formtxt fleft">Select Community</div>
					<div class="rtform fleft"><select class="homeselect" name="community"><option value="0">-------Select your Community-------</option>
					<option value="addharmi">Addharmi</option>
					<option value="adidravidar">Adidravidar</option>
					<option value="agarwal">Agarwal</option>
					<option value="agri">Agri</option>
					<option value="ahom">Ahom</option>
					<option value="ambalavasi">Ambalavasi</option>
					<option value="arekatica">Arekatica</option>
					<option value="arora">Arora</option>
					<option value="arunthathiyar">Arunthathiyar</option>
					<option value="aryavysya">Aryavysya</option>
					<option value="badagar">Badagar</option>
					<option value="baidya">Baidya</option>
					<option value="baishnab">Baishnab</option>
					<option value="baishya">Baishya</option>
					<option value="balija">Balija</option>
					<option value="banik">Banik</option>
					<option value="baniya">Baniya</option>
					<option value="banjara">Banjara</option>
					<option value="barai">Barai</option>
					<option value="bari">Bari</option>
					<option value="barujibi">Barujibi</option>
					<option value="besta">Besta</option>
					<option value="bhandari">Bhandari</option>
					<option value="bhatia">Bhatia</option>
					<option value="bhatraju">Bhatraju</option>
					<option value="bhovi">Bhovi</option>
					<option value="billava">Billava</option>
					<option value="boyer">Boyer</option>
					<option value="brahmbatt">Brahmbatt</option>
					<option value="brahmin">Brahmin</option>
					<option value="chambhar">Chambhar</option>
					<option value="chandravanshikahar">Chandravanshikahar</option>
					<option value="chasa">Chasa</option>
					<option value="chattadasrivaishnava">Chattadasrivaishnava</option>
					<option value="chaudary">Chaudary</option>
					<option value="chaurasia">Chaurasia</option>
					<option value="chettiyar">Chettiyar</option>
					<option value="chhetri">Chhetri</option>
					<option value="chippolu">Chippolu</option>
					<option value="ckp">Ckp</option>
					<option value="coorg">Coorg</option>
					<option value="devadiga">Devadiga</option>
					<option value="devanga">Devanga</option>
					<option value="devangkoshthi">Devangkoshthi</option>
					<option value="dhanghar">Dhanghar</option>
					<option value="dheevara">Dheevara</option>
					<option value="dhiman">Dhiman</option>
					<option value="dhoba">Dhoba</option>
					<option value="dhobi">Dhobi</option>
					<option value="dumal">Dumal</option>
					<option value="dusadh">Dusadh</option>
					<option value="ediga">Ediga</option>
					<option value="ezhava">Ezhava</option>
					<option value="ezhuthachan">Ezhuthachan</option>
					<option value="gabit">Gabit</option>
					<option value="gandla">Gandla</option>
					<option value="ganiga">Ganiga</option>
					<option value="garhwal">Garhwal</option>
					<option value="gavara">Gavara</option>
					<option value="gawali">Gawali</option>
					<option value="ghisadi">Ghisadi</option>
					<option value="ghumar">Ghumar</option>
					<option value="goala">Goala</option>
					<option value="gomantak">Gomantak</option>
					<option value="gondhali">Gondhali</option>
					<option value="goud">Goud</option>
					<option value="goundar">Goundar</option>
					<option value="gowda">Gowda</option>
					<option value="gramini">Gramini</option>
					<option value="gudia">Gudia</option>
					<option value="gujjar">Gujjar</option>
					<option value="gupta">Gupta</option>
					<option value="guptan">Guptan</option>
					<option value="gurav">Gurav</option>
					<option value="gurjar">Gurjar</option>
					<option value="gurukkal">Gurukkal</option>
					<option value="hugar">Hugar</option>
					<option value="irani">Irani</option>
					<option value="iyengar">Iyengar</option>
					<option value="iyer">Iyer</option>
					<option value="jaalari">Jaalari</option>
					<option value="jaiswal">Jaiswal</option>
					<option value="jandra">Jandra</option>
					<option value="jangam">Jangam</option>
					<option value="jat">Jat</option>
					<option value="jatav">Jatav</option>
					<option value="jogi">Jogi</option>
					<option value="kachara">Kachara</option>
					<option value="kaibarta">Kaibarta</option>
					<option value="kalar">Kalar</option>
					<option value="kalinga">Kalinga</option>
					<option value="kalita">Kalita</option>
					<option value="kalwar">Kalwar</option>
					<option value="kamboj">Kamboj</option>
					<option value="kammachowdary">Kammachowdary</option>
					<option value="kansari">Kansari</option>
					<option value="kapunaidu">Kapunaidu</option>
					<option value="karana">Karana</option>
					<option value="karmakar">Karmakar</option>
					<option value="karuneegar">Karuneegar</option>
					<option value="kasar">Kasar</option>
					<option value="kashyap">Kashyap</option>
					<option value="katiya">Katiya</option>
					<option value="kayastha">Kayastha</option>
					<option value="khandayat">Khandayat</option>
					<option value="khandelwal">Khandelwal</option>
					<option value="kharwar">Kharwar</option>
					<option value="khatri">Khatri</option>
					<option value="koiri">Koiri</option>
					<option value="koli">Koli</option>
					<option value="konguvelalagounder">Konguvelalagounder</option>
					<option value="konkan">Konkan</option>
					<option value="kori">Kori</option>
					<option value="kshatriya">Kshatriya</option>
					<option value="kudumbi">Kudumbi</option>
					<option value="kulal">Kulal</option>
					<option value="kulalar">Kulalar</option>
					<option value="kulita">Kulita</option>
					<option value="kumawat">Kumawat</option>
					<option value="kumbhakar">Kumbhakar</option>
					<option value="kumbhar">Kumbhar</option>
					<option value="kumhar">Kumhar</option>
					<option value="kummari">Kummari</option>
					<option value="kunbi">Kunbi</option>
					<option value="kuravan">Kuravan</option>
					<option value="kurmi">Kurmi</option>
					<option value="kuruba">Kuruba</option>
					<option value="kuruhinashetty">Kuruhinashetty</option>
					<option value="kurumbar">Kurumbar</option>
					<option value="lingayath">Lingayath</option>
					<option value="lohana">Lohana</option>
					<option value="lubana">Lubana</option>
					<option value="madiga">Madiga</option>
					<option value="mahajan">Mahajan</option>
					<option value="mahar">Mahar</option>
					<option value="mahendra">Mahendra</option>
					<option value="maheshwari">Maheshwari</option>
					<option value="mahishya">Mahishya</option>
					<option value="majabi">Majabi</option>
					<option value="mala">Mala</option>
					<option value="mali">Mali</option>
					<option value="malla">Malla</option>
					<option value="mangalorean">Mangalorean</option>
					<option value="manipuri">Manipuri</option>
					<option value="mapila">Mapila</option>
					<option value="maratha">Maratha</option>
					<option value="maruthuvar">Maruthuvar</option>
					<option value="matang">Matang</option>
					<option value="mathur">Mathur</option>
					<option value="meena">Meena</option>
					<option value="meenavar">Meenavar</option>
					<option value="mehra">Mehra</option>
					<option value="merudarji">Merudarji</option>
					<option value="modak">Modak</option>
					<option value="mogaveera">Mogaveera</option>
					<option value="mudaliyar">Mudaliyar</option>
					<option value="mudiraj">Mudiraj</option>
					<option value="mukulathor">Mukulathor</option>
					<option value="muthuraja">Muthuraja</option>
					<option value="naagavamsam">Naagavamsam</option>
					<option value="nagaralu">Nagaralu</option>
					<option value="nai">Nai</option>
					<option value="naicker">Naicker</option>
					<option value="naik">Naik</option>
					<option value="nair">Nair</option>
					<option value="nambiar">Nambiar</option>
					<option value="namosudra">Namosudra</option>
					<option value="napit">Napit</option>
					<option value="nayaka">Nayaka</option>
					<option value="neeli">Neeli</option>
					<option value="nepali">Nepali</option>
					<option value="nhavi">Nhavi</option>
					<option value="oswal">Oswal</option>
					<option value="otari">Otari</option>
					<option value="padmasali">Padmasali</option>
					<option value="pal">Pal</option>
					<option value="panchal">Panchal</option>
					<option value="panicker">Panicker</option>
					<option value="parkavakulam">Parkavakulam</option>
					<option value="partraj">Partraj</option>
					<option value="pasi">Pasi</option>
					<option value="patel">Patel</option>
					<option value="patnaick">Patnaick</option>
					<option value="patra">Patra</option>
					<option value="perika">Perika</option>
					<option value="porwal">Porwal</option>
					<option value="prajapati">Prajapati</option>
					<option value="raigar">Raigar</option>
					<option value="rajaka">Rajaka</option>
					<option value="rajastani">Rajastani</option>
					<option value="rajbonshi">Rajbonshi</option>
					<option value="rajput">Rajput</option>
					<option value="ramdasia">Ramdasia</option>
					<option value="ramgariah">Ramgariah</option>
					<option value="ravidasia">Ravidasia</option>
					<option value="rawat">Rawat</option>
					<option value="reddy">Reddy</option>
					<option value="relli">Relli</option>
					<option value="sadgope">Sadgope</option>
					<option value="saha">Saha</option>
					<option value="sahu">Sahu</option>
					<option value="saini">Saini</option>
					<option value="saliya">Saliya</option>
					<option value="savji">Savji</option>
					<option value="sc">SC</option>
					<option value="senaithalaivar">Senaithalaivar</option>
					<option value="settibalija">Settibalija</option>
					<option value="shetty">Shetty</option>
					<option value="shimpi">Shimpi</option>
					<option value="skp">Skp</option>
					<option value="sonar">Sonar</option>
					<option value="sourashtra">Sourashtra</option>
					<option value="st">ST</option>
					<option value="sugali">Sugali</option>
					<option value="sunari">Sunari</option>
					<option value="sundhi">Sundhi</option>
					<option value="suthar">Suthar</option>
					<option value="swakulasali">Swakulasali</option>
					<option value="tamboli">Tamboli</option>
					<option value="tanti">Tanti</option>
					<option value="tantubai">Tantubai</option>
					<option value="telaga">Telaga</option>
					<option value="teli">Teli</option>
					<option value="thakkar">Thakkar</option>
					<option value="thakur">Thakur</option>
					<option value="thigala">Thigala</option>
					<option value="thiyya">Thiyya</option>
					<option value="tili">Tili</option>
					<option value="togata">Togata</option>
					<option value="turupukapu">Turupukapu</option>
					<option value="uppara">Uppara</option>
					<option value="vadabalija">Vadabalija</option>
					<option value="vaddera">Vaddera</option>
					<option value="vaish">Vaish</option>
					<option value="vaishnav">Vaishnav</option>
					<option value="vaishnava">Vaishnava</option>
					<option value="vaishya">Vaishya</option>
					<option value="vaishyavani">Vaishyavani</option>
					<option value="valluvan">Valluvan</option>
					<option value="valmiki">Valmiki</option>
					<option value="vania">Vania</option>
					<option value="vanjara">Vanjara</option>
					<option value="vanjari">Vanjari</option>
					<option value="vankar">Vankar</option>
					<option value="vannar">Vannar</option>
					<option value="vanniakulakshatriya">Vanniakulakshatriya</option>
					<option value="variar">Variar</option>
					<option value="veerasaivam">Veerasaivam</option>
					<option value="velaan">Velaan</option>
					<option value="vellalar">Vellalar</option>
					<option value="vettuvagounder">Vettuvagounder</option>
					<option value="vishwakarma">Vishwakarma</option>
					<option value="viswabrahmin">Viswabrahmin</option>
					<option value="vokkaliga">Vokkaliga</option>
					<option value="vysya">Vysya</option>
					<option value="yadhav">Yadhav</option>
					<option value="yellapu">Yellapu</option>
					<option value="">----------- Exclusive Site ------------</option>
					<option value="divorcee">Divorcee</option></select></div>
					</div>
					<div class="ltform formtxt fleft">Country living in</div>
					<div class="rtform fleft"><select class="homeselect" name="country"><option value="0">-------- Select your Country --------</option>
					<option value="98">India</option>
					<option value="222">United States of America</option>
					<option value="220">United Arab Emirates</option>
					<option value="129">Malaysia</option>
					<option value="221">United Kingdom</option>
					<option value="13">Australia</option>
					<option value="185">Saudi Arabia</option>
					<option value="39">Canada</option>
					<option value="189">Singapore</option>
					<option value="114">Kuwait</option>
					<option value="">-------------------------</option>
					<option value="1">Afghanistan</option>
					<option value="2">Albania</option>
					<option value="3">Algeria</option>
					<option value="4">American Samoa</option>
					<option value="5">Andorra</option>
					<option value="6">Angola</option>
					<option value="7">Anguilla</option>
					<option value="8">Antarctica</option>
					<option value="9">Antigua and Barbuda</option>
					<option value="10">Argentina</option>
					<option value="11">Armenia</option>
					<option value="12">Aruba</option>
					<option value="237">Ashmore and Cartier Islands</option>
					<option value="14">Austria</option>
					<option value="15">Azerbaijan</option>
					<option value="16">Bahamas</option>
					<option value="17">Bahrain</option>
					<option value="18">Bangladesh</option>
					<option value="19">Barbados</option>
					<option value="239">Bassas da India</option>
					<option value="20">Belarus</option>
					<option value="21">Belgium</option>
					<option value="22">Belize</option>
					<option value="23">Benin</option>
					<option value="24">Bermuda</option>
					<option value="25">Bhutan</option>
					<option value="254">Bodies of water</option>
					<option value="26">Bolivia</option>
					<option value="27">Bosnia and Herzegovina</option>
					<option value="28">Botswana</option>
					<option value="29">Bouvet Island</option>
					<option value="30">Brazil</option>
					<option value="31">British Indian Ocean Territory</option>
					<option value="32">British Virgin Islands</option>
					<option value="33">Brunei</option>
					<option value="34">Bulgaria</option>
					<option value="35">Burkina Faso</option>
					<option value="36">Burundi</option>
					<option value="37">Cambodia</option>
					<option value="38">Cameroon</option>
					<option value="40">Cape Verde</option>
					<option value="41">Cayman Islands</option>
					<option value="42">Central African Republic</option>
					<option value="43">Chad</option>
					<option value="44">Chile</option>
					<option value="45">China</option>
					<option value="46">Christmas Island</option>
					<option value="248">Clipperton Island</option>
					<option value="47">Cocos Islands</option>
					<option value="48">Colombia</option>
					<option value="49">Comoros</option>
					<option value="50">Congo</option>
					<option value="240">Congo (Brazzaville)</option>
					<option value="51">Cook Islands</option>
					<option value="241">Coral Sea Islands</option>
					<option value="52">Costa Rica</option>
					<option value="249">Cote DIvoire</option>
					<option value="53">Croatia</option>
					<option value="54">Cuba</option>
					<option value="55">Cyprus</option>
					<option value="56">Czech Republic</option>
					<option value="57">Denmark</option>
					<option value="58">Djibouti</option>
					<option value="59">Dominica</option>
					<option value="60">Dominican Republic</option>
					<option value="61">East Timor</option>
					<option value="62">Ecuador</option>
					<option value="63">Egypt</option>
					<option value="64">El Salvador</option>
					<option value="65">Equatorial Guinea</option>
					<option value="66">Eritrea</option>
					<option value="67">Estonia</option>
					<option value="68">Ethiopia</option>
					<option value="243">Europa Island</option>
					<option value="69">Falkland Islands</option>
					<option value="70">Faroe Islands</option>
					<option value="71">Fiji</option>
					<option value="72">Finland</option>
					<option value="73">France</option>
					<option value="74">French Guiana</option>
					<option value="75">French Polynesia</option>
					<option value="76">French Southern Territories</option>
					<option value="77">Gabon</option>
					<option value="78">Gambia</option>
					<option value="246">Gaza Strip</option>
					<option value="79">Georgia</option>
					<option value="80">Germany</option>
					<option value="81">Ghana</option>
					<option value="82">Gibraltar</option>
					<option value="245">Glorioso Islands</option>
					<option value="83">Greece</option>
					<option value="84">Greenland</option>
					<option value="85">Grenada</option>
					<option value="86">Guadeloupe</option>
					<option value="87">Guam</option>
					<option value="88">Guatemala</option>
					<option value="244">Guernsey</option>
					<option value="89">Guinea</option>
					<option value="90">Guinea-Bissau</option>
					<option value="91">Guyana</option>
					<option value="92">Haiti</option>
					<option value="93">Heard and McDonald Islands</option>
					<option value="94">Honduras</option>
					<option value="95">Hong Kong</option>
					<option value="96">Hungary</option>
					<option value="97">Iceland</option>
					<option value="99">Indonesia</option>
					<option value="100">Iran</option>
					<option value="101">Iraq</option>
					<option value="102">Ireland</option>
					<option value="247">Isle of Man</option>
					<option value="103">Israel</option>
					<option value="104">Italy</option>
					<option value="105">Ivory Coast</option>
					<option value="106">Jamaica</option>
					<option value="251">Jan Mayen</option>
					<option value="107">Japan</option>
					<option value="250">Jersey</option>
					<option value="108">Jordan</option>
					<option value="252">Juan de Nova Island</option>
					<option value="109">Kazakhstan</option>
					<option value="110">Kenya</option>
					<option value="111">Kiribati</option>
					<option value="112">Korea, North</option>
					<option value="113">Korea, South</option>
					<option value="115">Kyrgyzstan</option>
					<option value="116">Laos</option>
					<option value="117">Latvia</option>
					<option value="118">Lebanon</option>
					<option value="119">Lesotho</option>
					<option value="120">Liberia</option>
					<option value="121">Libya</option>
					<option value="122">Liechtenstein</option>
					<option value="123">Lithuania</option>
					<option value="124">Luxembourg</option>
					<option value="125">Macau</option>
					<option value="253">Macedonia</option>
					<option value="126">Macedonia, Former Yugoslav Republic of</option>
					<option value="127">Madagascar</option>
					<option value="128">Malawi</option>
					<option value="130">Maldives</option>
					<option value="131">Mali</option>
					<option value="132">Malta</option>
					<option value="133">Marshall Islands</option>
					<option value="134">Martinique</option>
					<option value="135">Mauritania</option>
					<option value="136">Mauritius</option>
					<option value="137">Mayotte</option>
					<option value="138">Mexico</option>
					<option value="139">Micronesia, Federated States of</option>
					<option value="140">Moldova</option>
					<option value="141">Monaco</option>
					<option value="142">Mongolia</option>
					<option value="143">Montserrat</option>
					<option value="144">Morocco</option>
					<option value="145">Mozambique</option>
					<option value="146">Myanmar</option>
					<option value="147">Namibia</option>
					<option value="148">Nauru</option>
					<option value="149">Nepal</option>
					<option value="150">Netherlands</option>
					<option value="151">Netherlands Antilles</option>
					<option value="152">New Caledonia</option>
					<option value="153">New Zealand</option>
					<option value="154">Nicaragua</option>
					<option value="155">Niger</option>
					<option value="156">Nigeria</option>
					<option value="157">Niue</option>
					<option value="158">Norfolk Island</option>
					<option value="159">Northern Mariana Islands</option>
					<option value="160">Norway</option>
					<option value="161">Oman</option>
					<option value="162">Pakistan</option>
					<option value="163">Palau</option>
					<option value="164">Panama</option>
					<option value="165">Papua New Guinea</option>
					<option value="255">Paracel Islands</option>
					<option value="166">Paraguay</option>
					<option value="167">Peru</option>
					<option value="168">Philippines</option>
					<option value="169">Pitcairn Island</option>
					<option value="170">Poland</option>
					<option value="171">Portugal</option>
					<option value="172">Puerto Rico</option>
					<option value="173">Qatar</option>
					<option value="174">Reunion</option>
					<option value="175">Romania</option>
					<option value="176">Russia</option>
					<option value="177">Rwanda</option>
					<option value="178">S. Georgia and S. Sandwich Isls.</option>
					<option value="258">Saint Helena</option>
					<option value="179">Saint Kitts & Nevis</option>
					<option value="180">Saint Lucia</option>
					<option value="257">Saint Pierre and Miquelon</option>
					<option value="262">Saint Vincent & the Grenadines</option>
					<option value="181">Saint Vincent and The Grenadines</option>
					<option value="182">Samoa</option>
					<option value="183">San Marino</option>
					<option value="184">Sao Tome and Principe</option>
					<option value="186">Senegal</option>
					<option value="265">Serbia and Montenegro</option>
					<option value="187">Seychelles</option>
					<option value="188">Sierra Leone</option>
					<option value="190">Slovakia</option>
					<option value="191">Slovenia</option>
					<option value="238">Solomon Islands</option>
					<option value="192">Somalia</option>
					<option value="193">South Africa</option>
					<option value="194">Spain</option>
					<option value="256">Spratly Islands</option>
					<option value="195">Sri Lanka</option>
					<option value="196">St. Helena</option>
					<option value="197">St. Pierre and Miquelon</option>
					<option value="198">Sudan</option>
					<option value="199">Suriname</option>
					<option value="259">Svalbard</option>
					<option value="200">Svalbard and Jan Mayen Islands</option>
					<option value="201">Swaziland</option>
					<option value="202">Sweden</option>
					<option value="203">Switzerland</option>
					<option value="204">Syria</option>
					<option value="205">Taiwan</option>
					<option value="206">Tajikistan</option>
					<option value="207">Tanzania</option>
					<option value="208">Thailand</option>
					<option value="209">Togo</option>
					<option value="210">Tokelau</option>
					<option value="211">Tonga</option>
					<option value="212">Trinidad and Tobago</option>
					<option value="260">Tromelin Island</option>
					<option value="213">Tunisia</option>
					<option value="214">Turkey</option>
					<option value="215">Turkmenistan</option>
					<option value="216">Turks and Caicos Islands</option>
					<option value="217">Tuvalu</option>
					<option value="218">Uganda</option>
					<option value="219">Ukraine</option>
					<option value="261">Undersea features</option>
					<option value="223">Uruguay</option>
					<option value="224">Uzbekistan</option>
					<option value="225">Vanuatu</option>
					<option value="226">Vatican City</option>
					<option value="227">Venezuela</option>
					<option value="228">Vietnam</option>
					<option value="229">Virgin Islands</option>
					<option value="264">Wallis and Futuna</option>
					<option value="230">Wallis and Futuna Islands</option>
					<option value="263">West Bank</option>
					<option value="231">Western Sahara</option>
					<option value="232">Yemen</option>
					<option value="233">Yugoslavia (Former)</option>
					<option value="234">Zaire</option>
					<option value="235">Zambia</option>
					<option value="236">Zimbabwe</option></select></div>
					<div class="ltform formtxt fleft">Mobile No.<br>and/or</div>
					<div class="rtform fleft"><input type="text" class="inputtext" style="width:50px;" value="91" name="countryCode" />&nbsp;<input type="text" class="inputtext" style="width:137px;" maxlength="10" name="mobileNo" /></div><br clear="all">
					<div class="ltform formtxt fleft">Landline No.</div>
					<div class="rtform fleft"><input type="text" class="inputtext" style="width:50px;" value="" name="areaCode" />&nbsp;<input type="text" class="inputtext" style="width:137px;" maxlength="8" name="phoneNo" /></div>
					<div class="ltform formtxt fleft">E-mail</div>
					<div class="rtform fleft"><input type="text" class="inputtext" name="email" /></div>
					<div class="ltform formtxt fleft">Login Password</div>
					<div class="rtform fleft"><input type="password" class="inputtext" name="password" style="width:127px;" /><img src="http://img.muslimmatrimony.com/images/trans.gif" height="1" width="15" /><input type="submit" class="button" value="Submit" /></div>
				</div>
			</form>
			</center>
		</div><br clear="all"><img src="http://img.muslimmatrimony.com/images/trans.gif" width="1" height="3" /><br clear="all">
		<div class="tabdiv" id="mustxtdiv" style="display:block;">
			<div style="width:420px !important;width:470px;padding:25px;line-height:16px;" class="smalltxt fleft tljust"><font class="headtxt clr1 bld">MuslimMatrimony.com</font><br><br>Islam is a complete way of life, implying a total submission to God. One who surrenders his or her will to God, voluntarily, is called a Muslim. For Muslims marriage completes half of their faith. At MuslimMatrimony.com we want to help you find that best half. You can select a partner from any denomination. We have a host of search options that will help you find the most compatible partner from our vast database of Muslim profiles across the globe.</div>
			<div class="fright smalltxt tlleft" style="width:250px !important;width:300px;padding:50px 25px 0px 25px;">
				<div class="bulletdiv normtxt">Profiles from the <b>Muslim community</b> only</div><img src="http://img.muslimmatrimony.com/images/trans.gif" width="1" height="10" /><br clear="all">
				<div class="bulletdiv normtxt">Lakhs of global profiles</div><img src="http://img.muslimmatrimony.com/images/trans.gif" width="1" height="10" /><br clear="all">
				<div class="bulletdiv normtxt">Free and easy profile registration</div>
			</div>
		</div>
		<br clear="all">
		<div class="footdiv smalltxt clr2 lh16"><a class="clr2" href="http://www.communitymatrimony.com/homepages/community/termsandconditions.html">Terms and Conditions</a>&nbsp;|&nbsp;<a href="http://www.communitymatrimony.com/homepages/community/privacypolicy.html" class="clr2">Privacy Policy</a><br>Copyright &copy; 2009 Consim Info Pvt Ltd. All rights reserved.</div><br>
	</div>
</div>
</center>
 </BODY>
</HTML>