var ajobj;
var upimg= varConfArr['domainimgs']+"/rp-arrow-up.gif";
var downimg= varConfArr['domainimgs']+"/rp-arrow-down.gif";
function $BN(dn,s) { var d=$(dn); (s=="b") ? ss="block" : ss="none"; if(d!='') { d.style.display=ss; } }
function dv(obj){if(document.getElementById){if(document.getElementById(obj)!=null){return document.getElementById(obj)}else{return"";}}else if(document.all){if(document.all[obj]!=null){return document.all[obj]}else{return"";}}}function showscore(c){var c;var x=dv('ardown');var x1=dv('scoreshowdown');var y=dv('arup');var y1=dv('scoreshowup');y1.style.display="block";if(c.length<1){return;}if(dv(c).style.display=="none"){dv(c).style.display="block";x.style.display="none";x1.style.display="none";y.style.display="block";y1.style.display="block";}else{dv(c).style.display="none";x.style.display="block";x1.style.display="block";y.style.display="none";y1.style.display="none";}}var openval="";var imgval="";
function promotioncontent(divid,imgid){if((dv('faq1')!="null")&&(dv('faq1')!="")){if(divid!="faq1"&&dv("faq1").style.display=="block"){dv("faq1").style.display="none";dv("faq1-title").innerHTML="";dv("faq1-title").innerHTML="<img src="+upimg+">";}}if(openval==divid){if(dv(openval).style.display=="block"){dv(imgval).innerHTML="";dv(imgval).innerHTML="<img src="+upimg+">";dv(openval).style.display="none";}else{dv(imgval).innerHTML="";dv(imgval).innerHTML="<img src="+downimg+">";dv(openval).style.display="block";}}else{if(openval!=""){dv(openval).style.display="none";dv(imgval).innerHTML="";dv(imgval).innerHTML="<img src="+upimg+">";}if(dv(divid).style.display=="none"){dv(imgid).innerHTML="";dv(imgid).innerHTML="<img src="+downimg+">";dv(divid).style.display="block";}else{dv(imgid).innerHTML="";dv(imgid).innerHTML="<img src="+upimg+">";dv(divid).style.display="none";}}openval=divid;imgval=imgid;}function openpop(wname,wurl,wscroll,wresize,wwidth,wheight){try{var otheropt="top=250,left=525,bottom=0,toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars="+wscroll+",resize="+wresize+",width="+wwidth+",height="+wheight;var newwin=window.open(wurl,wname,otheropt);newwin.focus();} catch (e) {}}var succObj='';function successstorynxt(argNum,argdomain){var argUrl="/successstory/successstorypop.php?fileno="+argNum+"&domain="+argdomain;succObj=MakeGetRequest(argUrl,'succDiv');}function succDiv(){if(succObj.readyState==4){if(succObj.status==200){document.getElementById('dispcontent').style.display="block";document.getElementById('dispcontent').innerHTML=succObj.responseText;}else{alert('There was a problem with the request.');}}}function successstorypop(argNum,argdomain){var argUrl="/successstory/successstorypop.php?fileno="+argNum+"&domain="+argdomain;
openpop('successstory',argUrl,1,0,630,500);}
var succrightObj = '';
function successrightrandom(){
var argUrl="/successstory/successright.php?sucp="+genNumbers();
//succrightObj=MakeGetRequest(argUrl,'succRightDiv');
if($('rpanelsuccessstory')){ $('rpanelsuccessstory').src=argUrl; }
}function succRightDiv(){if(succrightObj.readyState==4){if(succrightObj.status==200){if($('successrightdiv')) {$('successrightdiv').style.display="block";$('successrightdiv').innerHTML=succrightObj.responseText;}}else{alert('There was a problem with the request.');}}}
var ping;var set_ping;