<div class="rpanel fleft">
	<center>
	<div class="padb10"><img src="<?=$confValues['IMGSURL']?>/banners/onlinepay2.gif" alt="" /></div><br clear="all">
	<div class="rpanelinner">
		<div class="normtxt clr padb5 bld">Click on your bank's link below to register your card:</div><br clear="all">
		<div class="normtxt clr2 lh20"><a href="https://netsafe.hdfcbank.com/ACSWeb/enrolljsp/Registration1.jsp" class="clr1" target="blank">HDFC Bank</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="https://www.3dsecure.icicibank.com/ACSWeb/EnrollWeb/ICICIBank/main/reg0.jsp" target="blank" class="clr1">ICICI Bank</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="https://www.citibank.co.in/ssjsps/ssindex.do" target="blank" class="clr1">Citibank</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="http://www.hsbc.co.in/1/2/personal/credit-cards/secure-online-payment-services" target="blank" class="clr1">HSBC Bank</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="http://www.standardchartered.co.in/personal/credit-cards/en/3d_secure.html" target="blank" class="clr1">Standard Chartered</a> &nbsp;&nbsp;|&nbsp;&nbsp;<br> <a href="https://secure4.arcot.com/vpas/sbi_vbvisa/enroll/enroll.jsp?locale=en_US&bankid=6897" target="blank" class="clr1">State Bank of India</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="https://secure.axisbank.com/ACSWeb/EnrollWeb/AxisBank/main/reg0.jsp" target="blank" class="clr1">Axis Bank</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="https://secure6.arcot.com/vpas/abnMasterCard/enroll/enroll.jsp?locale=en_US&bankid=3753" target="blank" class="clr1">ABN Amro</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="https://www.dbindia.in/DeutscheBank/enrollment/newuser.jsp" target="blank" class="clr1">Deutsche Bank</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="https://cardsecurity.enstage.com/ACSWeb/EnrollWeb/KVB/main/reg0.jsp" target="blank" class="clr1">Karur Vysya</a></div>
		<div class="normtxt clr padt10 lh16 tljust">To make online payment safer, the RBI has made it mandatory, from 1st August onwards, for all online transactions to have an additional level of authentication. The additional level is a password that you will have to enter after entering your credit/debit card details. You will require this password for transacting on any website in India. This process will ensure that unauthorized individuals will not use your card to make payment online.</div>
	</div>
	</center>
</div>