<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Marriage Customs</font>
	</div>
	<div class="rpanel" style="background:url(<?=$confValues['IMGSURL']?>/infopg_bg.gif) no-repeat;">
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:30px;">
				The ceremonies associated with a Brahmin wedding are elaborate and usually spread across five days. First, the bride and bridegroom are made to sit under a canopy, usually with twelve pillars. In the old days, it functioned as a shelter from the heat of the sun. Under this alcove, well decorated for the occasion, the young couple are seated with their faces turned to the east.<br><br>
				The married women would then come in and wave lighted camphor before an image of the god to avert the evil eye. This ceremony is called arathi where all the gods are invited to the wedding and requested to remain throughout the ceremony. The god of obstacles is an important figure and greatly feared, since his displeasure might stand in the way of a happy ending. So his image is placed under the pandal to ensure everything goes off well.<br><br>
				The bridegroom must be able to show that he is "pure" or free from sin. However, he is merely called upon to offer on the second day a gift as a token of his purity. Traditionally, this is followed by a little piece of acting and is probably connected with Brahmin notions of ceremonial purity. The bridegroom expresses a desire to quit the village and go on a pilgrimage to Benares and wash off his sins in the sacred waters of the Ganges. He gets ready to undertake the travel in earnest and leaves home to the sound of music and accompanied by his relatives and friends.<br><br>
				But the party is soon met by his future father-in-law who begs him to give up his plan and offers him his daughter. The would-be pilgrim readily accepts the offer and they return together to the house. The ceremonies are then allowed to proceed and the next step is the tying of the thread, which is fastened to the right wrist of the groom and the left wrist of the bride, to show that they are now tied together for life.<br><br>
				Just before the tying of the thali, the Brahmins put a screen of silk between the bride and bridegroom, while certain prayers are being recited. Next a fire is lit and the homam or sacrifice to Agni, the god of fire, is performed. The groom and bride, hand in hand, walk seven times round the fire and so make "the seven steps" together - a symbol of everlasting friendship. As a last step, the groom touches the bride's ankle with a small stone, called the stone of sandal. Another important ceremony is the sprinkling of rice on the bride and bridegroom, each standing in a basket made of bamboo. This ceremony symbolises fertility.<br><br>
				The marriage rituals of the Tamil Brahmin community are well-defined and elaborate starting with the Nischaiyathartham or engagement ceremony. The engagement function mainly involves the drawing up of the "lagna patrika" or a paper specifiying the date, time and venue of the marriage. In the case of Iyers, the ceremony is held in the groom's residence but it is just the opposite with the Iyengars. Dinner and sweets are served by whoever is hosting the ceremony but the groom's family gift a sari to the bride.<br><br>
				<B>Pandakol:</B> The wedding celebrations commence a day before the wedding when the bride's family start decorating and purifying the mandap in which the rites are to be performed. Milk, saffron and kumkum are poured on the bottom of the bamboo poles placed at the four corners of the mandap.<br><br>
				<B>Vratham</B> or anointing the bride and groom: This is a ceremony to obtain the blessings from the departed elders of both families. A sacred yellow thread is tied on the wrists of the bride and groom and nine varieties of grains are sprinkled for the prosperity of the couple's new life together. These rituals are observed separately for the bride and groom. The function rounds off with an arthi.<br><br>
				<B>Wedding preparations:</B> The bride's family sends toiletries, a mirror, a basket filled with sweetmeats and a 'nadeshwaram' to the groom's family. The groom's aunt brings a dish of 'appams' (pancakes made from rice flour and jaggery) for this occasion, while the 'pujaris' usually tie the traditional 'dhoti' or 'panchakatcham' for the groom and apply 'vibhuti' or sacred ash in three horizontal lines on his forehead.<br><br>
				<B>Janavasam & Nischaiyartham:</B> This ritual held in a temple is a significant part of the marriage ceremonies as it provides an opportunity to the families to sort out any differences between them. The bride's family brings turmeric, betel leaves, nuts and clothes and garlands the groom even as sugar candy is distributed to all present. The groom is then escorted to a decorated car and the family leaves in a procession for the 'mandapam'.<br><br>
				Once the procession reaches the marriage venue, the bride is led outside by her close friends to get a glimpse of her future husband! An arthi is performed and a coconut broken to ward off evil. When the groom arrives at the venue, the bride's family welcome him with sandalwood paste, kumkum, rose water, sugar candy, garlands and perform an arthi. He is also given 'thiraattupal' (condensed and sweetened milk) even as the 'nadeshwaram' (traditional wind instrument) is played in his honour.<br><br>
				The groom is then led to mandap and the members of both families sit opposite each other and a 'lagna patrika' (marriage contract) is written and read aloud by the 'pujari'. 'Thamboolams' (platters of betel nuts, dry fruits, nuts, coconuts, turmeric and 'kumkum') and gifts are exchanged.<br><br>
				<B>Kashi Yatra:</B> Dressed in the traditional 'panchakatcham', holding an umbrella, a fan, a walking stick, and a towel containing 'dal' (lentils) and rice tied to his shoulder, the groom embarks on a mock pilgrimage. As he steps out of the 'mandapam', the bride's father pleads with him not to go off on a Kashi pilgrimage and marry his daughter instead. After much ado the groom accepts and returns to the 'mandappam' to get married!<br><br>
				<B>The Unjal:</B> The couple exchange garlands here and they are made to sit on a swing and the womenfolk smear their feet with milk, kumkum and sandalwood paste. This is to protect them from the evil eye.<br><br>
				<B>Kanyadhan:</B> The bride is given away in this ceremony. Amid the chanting of Vedic mantras, the pujari ignites the sacred fire. The groom is gifted a 'muhurtha veshti' (a four metre long silk dhoti) and a pattu (a 2 metre long silk fabric to be used as a stole). The bride is seated on her father's lap during the 'kanyadhan'. The bride and groom then together hold a coconut dipped in turmeric, while the bride's mother pours water onto the coconut.<br><br>
				<B>Mangalyadharanam:</B> The groom ties the sacred thali on the bride. In this ceremony the thali is placed on the bride's head along with a miniature piece of jewellery shaped like a yoke and the groom performs a puja with kumkum and flowers. He then ties the first knot of the thali around the bride's neck and his sister ties the other two.<br><br>
				<B>Sapthapathi:</B> Seven steps around the sacred fire: The bride's sari 'pallav' and the groom's 'angavastram' (shawl) are tied in a knot and the couple hold hands. The groom places his foot under the bride's and helps her to take the seven steps around the fire. Then he places the bride's foot on a grinding stone near the fire and slips silver rings or 'metti' on her toes. The couple is then shown the 'Dhruva Nakshatra' or the Pole Star, a symbol of permanence and the 'Arundhati Nakshatra' or symbol of purity and virtue.<br><br>
				<B>Laja Homam:</B> The bride's brother slings a bagful of puffed rice or 'laja' over his shoulder and gives fistfuls of the rice periodically to his sister who in turn offer it as a sacrifice to the sacred fire. After this ritual the couple are blessed by all present.<br><br>
				<B>Sesha Homam:</B> This is a symbolic ritual to invoke the blessings for healthy offspring with the groom tying a thread around the bride's hip.<br><br>
				<B>Gruhapravesam:</B> If the grooms' family lives in the same town, the bride is taken to her new home and made to sit on a 'manai' (low wooden plank) and fed milk and bananas. Her in-laws gift her with a sari and she is asked to light the sacred lamp in the god's room. If the groom's family does not live in the same town, this ceremony is performed in the 'mandapam' after completing the marriage rites.<br><br>
				<B>Seer Bakshanam:</B> The bride's parents prepare several sweets and savouries for the bride to take back with her to her husband's home. These are known as 'seer bakshanam' and are stored in decorated containers and later distributed amongst friends and relatives by the groom's family.<br><br>
			</div>
		</div>
	</center>
	</div>
</div>