<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Pride of the community</font>
	</div>
	<div class="linesep"><img src="images/trans.gif" height="1" width="1" /></div>
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:10px;">
            <img src="http://img.iyermatrimony.com/images/Iyer_pride.jpg" style="padding-right:12px;float:left;"/>Mani Ratnam is one of the most celebrated filmmakers in India today. He was born in Madurai and his parents named him Gopala Ratnam Subramaniam. He did his schooling at Vidya Mandir Senior Secondary School, Chennai. After graduating with a degree in commerce from Vivekananda College and an MBA from Jamnalal Bajaj Institute of Management Studies, he embarked on a career as a management consultant before turning filmmaker.<br /><br />
            Mani has a sharp eye for technical details in the art of filmmaking. He has worked with and also introduced some of the best music directors, cinematographers, art directors, dialogue writers and editors in India. Several international papers and books have been published on his critically acclaimed movies. He has worked with many of India's superstars, including Rajinikanth, Kamalhassan, Shah Rukh Khan, Anil Kapoor, Akkineni Nagarjuna, Mammootty and Mohanlal.<br /><br />
            Mani Ratnam made his directorial debut in 1983 with the Kannada film Pallavi Anu Pallavi, starring Anil Kapoor. The film boldly explored a relationship between a young man and an older woman.<br /><br />
            In 1986, Mani attained commercial success in Tamil Nadu with the romantic drama Mouna Ragam starring Revathi and Mohan. The film told the story of the friction between a newly wed couple, and remains famous to date as a relevant and realistic portrayal of romance among urban Tamils.<br /><br />
            The year 1987 saw Mani Ratnam mature as a filmmaker with his blockbuster Nayagan in which Kamal Haasan played a key role as a south Indian don in Mumbai. Time magazine acknowledged this movie as one of the 100 top movies at that time.<br /><br />
            With commercial success coming back to back, Mani wrote and directed Agni Natchathiram. He was praised for using new techniques especially camera framework during the shooting of songs in the film. His next film was Geethanjali in Telugu with Nagarjuna in the lead role. It told the story of an ill-fated couple suffering from terminal diseases. The Raghuvaran starring Anjali in 1990 was a beautiful story of an autistic child who changed the lives of people in a colony.<br /><br />
            He later made another underworld-themed Tamil film with Thalapathi in 1991 starring Rajnikanth and Mammooty. With a theme of friendship between a local don and a slum king, Thalapathi earned both critical acclaim and commercial success.<br /><br />
            With Thalapathi, Mani ended his association with music director Ilaiyaraaja, bringing in debutant music director A. R. Rahman to score his Tamil epic Roja. Rahman turned out to be Mani's greatest find. Roja, a romantic film, tackled the theme of terrorism in Kashmir. The film - starring Arvind Swamy and Madhoo - was released in 1992 and nominated for the Golden St. George Award at the Moscow International Film Festival; it was dubbed into other languages and was a huge hit in several regions.<br /><br />
            In 1994, a retrospective of his Tamil films was shown at the Toronto International Film Festival.  In 1995, Mani returned to Tamil language drama with Bombay starring Arvind Swamy and Manisha Koirala. It told the story of a Hindu-Muslim couple in the midst of the 1993 Bombay riots and bombings. Bombay was financially successful and applauded by the critics. It won the Special Award from the Political Film Society, the Wim Van Leer In Spirit of Freedom Award at the Jerusalem International Film Festival and the Gala Award at the Edinburgh International Film Festival.<br /><br />
            Mani considers his Iruvar, starring Mohanlal and Prakash Raj, his finest effort to date. Inspired by the true story of iconic Tamil film star and politician MG Ramachandran and current Tamil Nadu Chief Minister M. Karunanidhi, it was hailed critically as a fine effort in filmmaking, winning Best Film at the Festival of the Auteur Films in Belgrade.<br /><br />
            Mani made his debut in Hindi with Dil Se. Ratnam used the conflict in the northeastern states as a backdrop to tell a love story between an Indian journalist and a northeastern woman. He returned to Tamil films with the romance drama Alaipayuthey, which explored post-marital problems between a young Chennai couple who married without their parents' consent. The film was a box-office hit and confirmed his stature as a director who knew exactly what film lovers wanted. <br /><br />
            His next effort was Kannathil Muthamittal, which tackled adoption through the eyes of a Tamil refugee from Sri Lanka searching for her biological mother. The film was a critically lauded commercial success, winning six National Film Awards, Mani's second Filmfare Award South for directing, his second In Spirit for Freedom Award at the Jerusalem Film Festival and an award at the Indian Film Festival of Los Angeles.<br /><br />
             In 2004, Mani made his second Hindi fim with Yuva. He also made the film simultaneously in Tamil as Aayutha Ezhuthu, The year 2007 saw Mani direct Guru starring Abhishek Bachchan. It became one of 2007's biggest hits.<br /><br />
             In 2010 Ratnam worked on a big-budget bilingual in Tamil and Hindi titled Raavanan in Tamil and Raavan in Hindi. The Tamil version was dubbed into Telugu as Villain. Many of his films have been dubbed or remade in several languages.<br /><br /><br />

            </div>

		</div>
	</center>
</div>