<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Wedding customs</font>
	</div>
	<div class="linesep"><img src="images/trans.gif" height="1" width="1" /></div>
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:10px;">
                <b>Rituals Before Marriage</b><br />
                <b>Tilak Ceremony</b><br />
                This is the official engagement ceremony wherein only the male members of the girl's family go to the boy's house. Only the bride's father, brother and other male relatives take part in this ceremony. No ladies accompany the men in this occasion. The ceremony, as its name suggests, has the girl's brother applying the tilak to the groom's forehead. The men from the girl's family usually present the boy with gifts such as a sword, other presents, clothes, sweets, fruits etc. This ceremony makes the engagement or alliance official.<br /><br />
                <b>Ganapati Sthapana and Griha Shanti Ceremony</b><br />
                Few days prior to the actual marriage, takes place the Ganapati Sthapana and Griha Shanti ceremony. These are held as very important as it takes place in lieu of the ring ceremony. The groom or bride's parents to propitiate the gods perform a havan and an idol of Lord Ganapati is installed. All ceremonies commence only after the sthapana (installation).<br /><br />
                <b>Pithi Dastoor Ceremony</b><br />
                This is an exquisite ceremony, which takes place at both the bride and the groom's places. This ritual applies to both the bride and the groom. It would continue till the final wedding day. The rites include the application of turmeric and sandal wood paste to the one going to get married. The bride and the groom would not be able to leave their respective houses as soon as the pithi starts. The pithi dastoor takes place on a large scale at the bride's house. For the occasion, the bride has to wear an orange Rajasthani dress. She is made to come under a silken canopy, which is held with the help of swords at the four corners by four ladies. These ladies eventually belong to the same clan. Then she is brought to the ladies gathering and these ladies then apply the paste to her. The pithi at the groom's place is held on a minor scale. Dholans (women singers with dholak) sing auspicious pre-wedding songs while the ceremony is in progress. Throughout the wedding celebrations, the dholans are omnipresent, along with the Shehnai and the nagara players, though the latter remain at the courtyard or the garden.<br /><br />
                <b>Mahira Dastoor</b><br />
                Mahira Dastoor is again a custom exclusive to the Kshatriyas only. It takes place at both the girl and the boy's houses. This particular ceremony involves the maternal uncle of either side. The maternal uncle alongwith his family arrives with much fanfare. The respective families receive him with many greetings. The uncle then gives clothes, jewellery and sweet delicacies to the entire family. It is a ceremony symbolic of the fact that the maternal uncle has to lend a hand of help at the expenditure that his sister undergoes during her child's marriage.<br /><br />
                <b>Janev Ceremony</b><br />
                Janev ceremony is an important ritual of the Hindu marriages. It has the rite of making the groom wear the sacred thread. Men wear the janev only. The groom is made to wear the janev on the eve of his becoming the householder. He is made to wear a saffron robe and perform a yagna with the priest. The Kshatriyas wear the saffron robe with the thought that the groom has two choices before him. One that of renouncing the world by becoming an ascetic and the other is of getting married and accepting the responsibilities of marriage. At the end of the yagna, the groom has to act as if he wants to become an ascetic by running away. And the maternal uncle tries to stop him and convince him to get married.<br /><br />
                <b>Palla Dastoor</b><br />
                Palla Dastoor is a custom quintessential to the Kshatriyas. It involves the people from the boy's family coming with the trousseau - known as the palla dastoor. A day or two before marriage some relatives from the boy's family come along with a set of things like the clothes and the jewellery, which the bride has to wear at the wedding and also some gifts.<br /><br />
                <b>Baraat</b><br />
                Kshatriya Baraat is different from all other Indian baraat styles. It is elegant, poised and individualistic. For one thing, the Kshatriya baraat is again an all men's affair. So, to speak it consists of only the gents of the groom's family. Ladies do not take part in the procession. As much as that there is no dancing as the baraat progresses through the street. The groom usually rides an elephant or a horse and carries a sword. Also, each of the other male members of the family carries a sword.<br /><br />
                <b>Marriage Rituals</b><br />
                The bride's mother takes the groom to the ladies section after performing the traditional Aarti. He is then led to the wedding mandap. In all this only a married male relative or a brother or a male cousin accompany him. The wedding takes pace as usual with the yagna fire and the vedic mantras. There are the pheras also. The only exceptional thing about the whole thing is that the bride has to keep her face hidden behind a long veil throughout the marriage. It is mostly attended by the women folk of the family, as the men of the house remain busy tending after the barati and other guests.<br /><br />
                <b>Rituals After Marriage</b><br />
                <b>Grihapravesh</b><br />
                Grihapravesh is actually the entry of the bride into her husband's house for the first time. There take place the essential puja and other rituals as the bride arrives at the sasural (father-in-law's house). There take place certain games between the bride and the groom, those alike to the usual games that take place in other Hindu weddings.<br /><br />
                <b>Pagelagni</b><br />
                The day following the grihapravesh, the pagelagni takes place. This is a ceremony where the bride, still in veil, is formally introduced to all the family members of the groom who bless her and give her gifts. The veil is then finally removed.<br /><br />
                <b>Celebrations</b><br />
                <b>Music & Dance</b><br />
                The Mehfils are the main attractions of the Rajasthani wedding. A mehfil is a place where the ladies of the house assemble for music and dance evening. There is of course a gents mehfil as well. At the ladies mehfil, the women collect together at an enclosed courtyard or hall. They are usually dressed in sparkling dresses of all colors. Then, they perform Ghoomar, a famous Rajasthani dance number. The bride at the mehfil is given the position of the guest of honor. Though she can also take part in the dance numbers but it is generally believed that she should not overdo it. As overdoing indicates that she is not a modest and well-behaved girl. The ladies mehfil at the boy's place is the same except for the groom being allowed to attend the only for ladies programme. The men's mehfils at both the girl and the boy's places have a different flavor altogether. In these mehfils, professional singers are being invited to perform and these are exclusive all male parties.<br /><br />
                <b>Cuisine</b><br />
                Kshatriya cuisine comprises vegetarian as well as non-vegetarain fare. The Kshatriyas who are Vaishnavs, those that worship Lord Krishna are strictly vegetarian and the cuisine includes the traditional Rajasthani dishes like the daal-bati. Daal-bati is a dish of cooked lentils and roasted balls of dough, served alongwith a number of dried or pickled berries cooked in different ways. The warrior classes among the Kshatriyas, those that have warriors as their ancestors, take non-vegetarian dishes. The food is again diverse, inclusive of the seafood and vegetarian dishes. Then, there are the tandoori mixed grill with chicken, lamb, fish, and shrimp, and a smattering of curry offerings.<br /><br />
            </div>
		</div>
	</center>
</div>