<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Pride of Community</font>
	</div>
	<div class="rpanel" style="background:url(<?=$confValues['IMGSURL']?>/infopg_bg.gif) no-repeat;">
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:30px;">
				<img src="<?=$confValues['IMGSURL']?>/prideimg_ten.jpg" align="right" hspace="5" /><b>Sachin Tendulkar: A Legend in his Lifetime!</b><br><br>
				One of the greatest players to have ever played the game, Sachin Ramesh Tendulkar has been the best known icon of world cricket for almost two decades now. Ever since his debut way back in 1989, he displayed exemplary skills when at the crease and was immediately hailed as the next genius. Sachin did not disappoint anyone and cruised his way into the record books with each knock. The mid-90s saw him peak and every opposition feared the 'Little Master'.<br><br>
				According to experts, Sachin's batting is based on the purest principles: perfect balance, economy of movement, precision in stroke-making, and that intangible quality given only to geniuses, anticipation. If he doesn't have a signature stroke - the upright, back-foot punch comes close - it is because he is equally proficient in each of the full range of orthodox shots (and plenty of improvised ones as well) and can pull them out at will. There are no apparent weaknesses in Tendulkar's game. He can score all around the wicket, off both front foot and back, can tune his technique to suit every condition, temper his game to suit every situation, and has made runs in all parts of the world in all conditions.<br><br>
				Some of his finest performances have come against Australia, the overwhelmingly dominant team of his era. His century as a 19-year old on a lightning fast pitch at the WACA is considered one of the best innings ever to have been played in Australia. A few years later he received the ultimate compliment from the ultimate batsman when Don Bradman confided to his wife that Tendulkar reminded him of himself.<br><br>
				Blessed with the keenest of cricket minds, and armed with a loathing for losing, Tendulkar set about doing what it took to become one of the best batsmen in the world. Tendulkar's greatness was established early: he was only 16 when he made his Test debut. He was hit on the mouth by Waqar Younis but continued to bat, in a blood-soaked shirt. His first Test hundred, a match-saving one at Old Trafford, came when he was 17, and he had 16 Test hundreds before he turned 25. In 2000 he became the first batsman to have scored 50 international hundreds, in 2008 he passed Brian Lara as the leading Test run-scorer and in the following years, he crossed 13,000 runs and 30,000 international runs.<br><br>
				He currently holds the record for most hundreds in both Tests and ODIs - remarkable, considering he didn't score his first ODI hundred till his 79th match. Incredibly, he retains a divine enthusiasm for the game, and he seems to be untouched by age: at 36 years and 306 days he broke a 40-year barrier by scoring the first double-century in one-day cricket. It now seems inevitable that he will become the first cricketer to score 100 international hundreds, which like Bradman's batting average, could last for ever.<br><br>
				His batting is based on simple principles and he does not possess any trademark stroke, although the straight drive comes close. Tendulkar's triumph has been his ability to adapt to situations, surfaces, oppositions and emerging victorious. He can score all around the wicket, off both front foot and back, and has made runs in all parts of the world. Don Bradman confessed that Tendulkar reminded him of himself and this perhaps speaks volumes of the latter's greatness.With infinite records to his name, Sachin is widely regarded as one of the greatest batsmen in the history of cricket. Each time he comes to bat, he carries the expectation of millions of people with him and comes good more often than not, which only reinforces the enormity of this genius. His opening partnerships with Sourav Ganguly marked one of the most successful phases of Indian cricket.<br><br>
				Tendulkar is one of the very few Indian players to never be dropped from the team and his consistency in Tests and ODIs is remarkable.He has suffered a few injuries but over the years India has developed firebrand cricketers like Virender Sehwag, MS Dhoni and Yuvraj Singh who have borne the burden of Tendulkar's former responsibility. But Tendulkar never takes things for granted and each passing year, he outdoes himself but creating another record. He already holds the record for most runs in Tests and ODIs and most centuries in both forms of the game. He deliberately omits himself from Twenty20 Internationals and that may have been his biggest regret as a young Indian team won the inaugural World Twenty20. As age catches up with him, he picks and chooses series he wishes to participate in.<br><br>
				Tendulkar was born in Bombay. His father, Ramesh Tendulkar, a Marathi novelist, named Tendulkar after his favourite music director, Sachin Dev Burman. Tendulkar's elder brother Ajit encouraged him to play cricket. Tendulkar has two other siblings: a brother Nitin and sister Savitai. He attended Sharadashram Vidyamandir where he began his cricketing career under the guidance of his coach and mentor, Ramakant Achrekar. During his school days he attended the MRF Pace Foundation to train as a fast bowler, but Australian fast bowler Dennis Lillee, who took a world record 355 Test wickets, was unimpressed, suggesting that Tendulkar focus on his batting instead.<br><br>
				When he was young, Tendulkar would practice for hours on end in the nets. If he became exhausted, Achrekar would put a one Rupee coin on the top of the stumps, and the bowler who dismissed Tendulkar would get the coin. If Tendulkar passed the whole session without getting dismissed, the coach would give him the coin. Tendulkar now considers the 13 coins he won then as some of his most prized possessions.<br><br>
				While at school, he developed a reputation as a child prodigy. He had become a common conversation point in Mumbai circles, where there were suggestions already that he would become one of the greats. His season in 1988 was extraordinary, with Tendulkar scoring a century in every innings he played. He was involved in an unbroken 664-run partnership in a Lord Harris Shield inter-school game in 1988 with friend and team mate Vinod Kambli, who would also go on to represent India. The destructive pair reduced one bowler to tears and made the rest of the opposition unwilling to continue the game. Tendulkar scored 326* in this innings and scored over a thousand runs in the tournament. This was a record partnership in any form of cricket until 2006, when it was broken by two under-13 batsmen in a match held at Hyderabad in India. 
				When he was 14, Indian batting legend Sunil Gavaskar gave him a pair of his own ultra light pads. "It was the greatest source of encouragement for me," he said nearly 20 years later after surpassing Gavaskar's world record of 34 Test centuries. On 24 May 1995, Sachin Tendulkar married Anjali, a paediatrician and daughter of Gujarati industrialist Anand Mehta. They have two children, Sara (born 12 October 1997), and Arjun (born 24 September 1999). Tendulkar sponsors 200 underprivileged children every year through Apnalaya, a Mumbai-based NGO associated with his mother-in-law, Annabel Mehta.<br><br>
				Tendulkar's considerable achievements seem greater still when looked at in the light of the burden of expectations he has had to bear from his adoring but somewhat unreasonable followers, who have been prone to regard anything less than a hundred as a failure. The aura may have dimmed, if only slightly, as the years on the international circuit have taken their toll on the body, but Tendulkar remains, by a distance, the most worshipped cricketer in the world. His ultimate goal is to sign off with a World Cup victory, which millions of Indians are hoping will come in his home-town India, in 2011.<br><br>
			</div>
		</div>
	</center>
	</div>
</div>