<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Wedding customs</font>
	</div>
	<div class="linesep"><img src="images/trans.gif" height="1" width="1" /></div>
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:10px;">
            The Buddhist views on marriage are very liberal. In Buddhism, marriage is considered as personal and individual concern, and not as a religious duty. Buddhism does not compel a person to be married. It does not force somebody to remain as a bachelor. It is not laid down anywhere that Buddhists must produce children or regulate the number of children that they produce. Buddhism allows each individual the freedom to decide for himself all the issues pertaining to marriage. It might be asked why Buddhist monks do not marry, since there are no laws for or against marriage. The reason is obviously that to be of service to mankind, the monks have chosen a way of life, which includes celibacy.<br /><br />
            <b>Marriage Through The Ages</b><br />
            Buddhist marriages have been considered as secular matters in Buddhist countries. The parties took a blessing from monks at the local temple after the civil registration formalities have been completed. Although Buddhist monks do not solemnize a marriage ceremony, they do perform religious services in order to bless the couples. From the Buddhist point of view, marriage is neither holy nor unholy. Buddhism does not regard marriage as a religious duty nor as a sacrament that is ordained in heaven.<br /><br />
            <b>Match Making</b><br />
            The matchmaking is usually done by taking the boy and the girl in confidence. It could be by the parents of either side or by the eligible boy himself. When the boy finds a suitable girl for him, he would usually send a family friend to the girl's house. The friend would generally carry a wine bottle or any other alcohol bottle for that matter. Additionally he carries a white silk scarf - khada. His role is to see whether the girl's family shows any inclination towards the proposal.<br /><br />
            <b>Costumes</b><br />
            <b>Bridal Wear</b><br />
            The Buddhist bride has her dress made of brocade called Bhaku. The dress resembles a sarong, only it has to be full length. The bride wears it with a sleeved blouse, Hanju. The hanju is usually made of Chinese silk called khichen. She also wears a special coat and a scarf. Some unusual jewellery (Khau) is also worn by her, those made of large precious and semi-precious stones for example turquoise, coral, pearl, etc. These jewellery would be worn around the neck and also on the forehead by traditional family girls. She would wear heavy gold bracelets in her arms too. The jewellery is mostly in pure gold or gold plated. The brides also wore special shoes and hat in the earlier days but this is not in fashion these days.<br /><br />
            <b>Groom's Attire</b><br />
            A Buddhist groom also wears a Bhaku, one that is with sleeves. The bhaku reaches to just above the ankles. The bhaku looks beautiful as it is made of brocade and is worn with a waistcoat called Lajha. The boy would also wear a cap, also made of brocade and a sash around the waist.<br /><br />
            <b>Rituals Before Marriage</b><br />
            <b>Khachang</b><br />
            Among the Buddhists either the parents or the boy choose his prospective bride. Once it is decided that you want to marry this particular girl, a family friend would usually go to the girl's house. He would carry a bottle of whisky and a white silk scarf called khada to offer. It is meant to see whether they give a nod to the proposal. This type of visit is usually known as Khachang. In case the family agree, the next step after Khachang is a meeting between the two families. In such a meeting, the members of both the families compare kikas. They set a good date on which the engagement can take place. Tradition has it that the boy presents a gift to his fiance. This gift could be as big as a land. The kika also decides about the colors of the dresses of the bride and the groom. Most of the marriages worldwide hold the notion that black color is not auspicious. Hot colors like those of red and gold are the preferred colors for the occasion.<br /><br />
            <b>Nangchang</b><br />
            This is the ceremony, which has the formal engagement-taking place. The Nangchang is presided over by a lama or rimpoche. The maternal uncles of both the sides play an important role in the ongoing marriage negotiations. On the boy's side, the mama and the siblings play important roles whereas the girl's side has the entire family, friends and the mama joining the occasion. The guests would bring Tsang and many kinds of meat to the girl's house. They gift rice and chicken especially to the girl's mother. This is a token payment to the mother for having breast-fed her girl. The meat and tsang are also given to the girl's mamas as well as to the unmarried elder sisters and brothers. The kikas would be matched again and an auspicious date for the marriage is fixed. A propitious day is also decided for the girl's departure from her maiden house. The young couple mostly live together either in the girl's or the boy's house after the engagement.<br /><br />
            <b>Marriage Rituals</b><br />
            Following are a set of fundamental rituals that commonly feature in Buddhist marriage:-<br />
                * In front of the shrine of Lord Buddha all set up with candles and flowers, the to-be married couple, the family and the guests would collect. The boy and the girl and others would recite the Tisarana, Pancasila and the Vandana in either English or Pali.<br />
                * The boy and the girl are asked to light the candles and incense sticks. Then they offer flowers to the image of Buddha and around it.<br />
                * After this the bride and the groom must recite in turn, the vows that are prescribed for each of them in the Sigilovdda Sutta (Digha Nikilya):<br />
                  Vow for the groom: "Towards my wife I undertake to love and respect her, be kind and considerate, be faithful, delegate domestic management, provide gifts to please her." Vow for the bride: "Towards my husband I undertake to perform my household duties efficiently, be hospitable to my in-laws and friends of my husband, be faithful, protect and invest our earnings, discharge my responsibilities lovingly and conscientiously."<br />
                * At the end, only the parents or the assembly would recite the Mangala Sutta and Jayamangala Gatha to offer their blessings for the couple. <br /><br />
                As for the Vidaai (girl's leaving maiden house for husband's house) ceremony, it is quite common for the newly wed couple to opt to stay at the girl's house. They could also decide to stay separately from either family.<br /><br />
                <b>Rituals after marriage</b><br />
            The girl's departure from her paternal house is also selected from the kika. This day could be any day between the first day after marriage till the tenth day.<br /><br />
            <b>Celebrations</b><br />
            <b>Music & Dance</b><br />
            Music and dance have been always a part and parcel of the marriage fair in Sikkim. The prime features of the occasion are Sangini, Nepali folk dance Maruni, Tamang Selo, Chufaat, Zo-mal-lok Bhutia folk dance, Singhi Cham, Yak Cham and Chabrung etc. The dances of Sikkim have little relationship with Indian traditions except in the cases of mask dances, which have the same format as the Buddhist dances still practiced. The women here have their independent folk dances but the men by and large are attracted only to the monastic versions.<br /><br />
            <b>Cuisine</b><br />
            The wedding feast would include meat dishes, the ones made of beef and pork. Rice dishes would be there also as rice is the staple food. Buddhists go for the oriental dishes, hence their dishes are generally steamed or roasted. They also have semi-fried or stewed food. The Buddhist feast has started including the usual North Indian dishes like those of Dal Makhani, Naan, Channa, Paneer, etc. Additionally, Indian sweets like Gajar ka Halwa, Gulab Jamun, are also increasingly found in the marriage menus. But typical Buddhist dishes like Nettle Soup, a variety of Orchid flower and cottage cheese, also cooked bamboo shoots are inevitably present. And last but not the least wine and similar alcoholic drinks should be kept in the Carte du jour. The indigenous tsang would always be found at the table. Tsang is offered to the groom in a special ceremonial vessel made of wood and wrapped with a carved silver foil, called hede pipe.<br /><br />

            </div>
		</div>
	</center>
</div>