<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Parenting after Divorce </font>
	</div>
	<div class="linesep"><img src="images/trans.gif" height="1" width="1" /></div>
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:10px;">
            The most difficult thing any parent in the world can experience is, telling their children that mom and dad will not be together anymore. That from now on the child will have only one parent living with him/her to share their day-to-day experiences of life. That the contours of his family cocoon is about to change quite drastically and that there is a lot of emotional and physical adjustment he/she will now have to make. But it is a moment that cannot be avoided once the decision to part has been taken. Divorce does no doubt, irrevocably and completely change the relationship that had existed between two people. But the fact is that even if the two cease to be husband and wife, they will always remain parents. No court of law can ever change this truth. <br /><br />
            Considering the hurt and pain that a child will inevitably experience at the loss of one of his parents, is it perhaps wiser to keep the marriage going for the sake of the child?  One school of thought would have it that children need both parents, specially the mother, therefore parents must put aside their differences or affairs and keep up the fa&#962;ade of marriage. But there is another group that believes otherwise. They say it is absolutely unwise to assume that children's best interests are served by parents staying together no matter how bad the marriage. According to them, staying together for the sake of the children alone can be far more destructive than any divorce. <br /><br />
            Saurabh Trehan who at 21, still bears the signs of stressful parenting, laments, "I don't know why my parents stayed together. They couldn't bear to be in the same room for more than five minutes. Each ran down the other publicly and I felt so ashamed of this that I could not concentrate on my studies. Dad would not give mom enough money to run the household and she became an alcoholic. God, it was terrible!" Many counselors now say that the impact of divorce is less stressful for children than the experience of remaining in a troubled home where the parents are not committed to working on their marriage. <br /><br />
            In the words of an eminent psychologist, "Divorce is clear; a troubled home is not. Divorce happens within a finite time; a troubled home does not! It is a destructive environment of confused relationships, anxiety and fear that can actually make children physically ill. It reinforces negative emotional patterns that can stay in place for the rest of their lives." <br /><br />
            Most parents refuse to acknowledge the fact that children know when something is wrong between their parents. If the marriage is in trouble, children know it, no matter what you tell them. The undercurrents of dissension in a family often leave the child with a guilt feeling. He thinks it is his fault that his parents are unhappy. On the other side, guilt often drives parents to buy the affection of their children at all costs - a terribly disastrous thing to do, I can assure you. <br /><br />
            Actually the most precious gift any parent can give their child is the assurance that: no matter what we do with our lives, we will always be available for you at all times. This kind of assurance can come only when parents are prepared to be responsible adults. The principles of the game remains the same - love your children, be honest with them and support them in becoming loving, able, self-reliant people. There is just no excuse for poor parenting! <br /><br />
                        </div>
		</div>
	</center>
</div>