<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Pride of the community</font>
	</div>
	<div class="linesep"><img src="images/trans.gif" height="1" width="1" /></div>
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:10px;">
            <img src="http://img.jatmatrimony.com/images/Jat_pride.jpg" style="padding-right:12px;float:left;"/>Virendra Sehwag is one of the most aggressive batsmen in international cricket today. Also known as Viru, he is a right-handed opening batsman and an occasional right-arm off-spin bowler.<br /><br />
            Sehwag was born on 20th October 1978 in Delhi and played his first One Day International in 1999 and joined the Indian Test cricket team in 2001. In April 2009, Sehwag became the only Indian to be honored as the 'Wisden Leading Cricketer' in the World for his performance in 2008. He became the first player of any nationality to retain the award for 2009.<br /><br />
            Sehwag was born in a Jat family from Haryana as the son of a grain merchant. He spent his childhood in a bungalow in a joint family with siblings, uncles, aunts and sixteen cousins. Sehwag was the third of four children born to Krishan and mother Krishna Sehwag. His father attributes his interest in cricket to a toy bat which he was given when he was seven months old. <br /><br />
            Sehwag attended Arora Vidya School in Delhi and pestered his parents to let him play cricket as he was not academically gifted. His father tried to end his career when he broke a tooth as a child in 1990, but he evaded the ban with a little help from his mother.<br /><br />
            Sehwag made his debut for Delhi cricket team in first class cricket in the 1997-98 season. He was selected to the North Zone cricket team for the Duleep Trophy the following 1998-99 season, ending fifth in the total run scoring list. The following year he was fourth on the Duleep Trophy run scoring list, including a 274, the highest score of the competition. This was against South Zone at Agartala in just 327 balls and followed a rapid 187 from just 175 in a Ranji Trophy match against Punjab.<br /><br />
            He was then selected for the U-19 team which toured South Africa. He was seventh in the 2000-01 season with two centuries, but his consistency earned the attention of selectors and he became a regular member in the national team in mid 2001.<br /><br />
            Sehwag made his Test match debut in 2001 as a middle-order batsman against South Africa with a century to his name, scoring 105. After the home series in 2001-02 against England and Zimbabwe, Sehwag was promoted up the order to open the innings in the 2002 England tour and he has remained in the order ever since. <br /><br />
            During the 2002-03 season, he scored his maiden home century of 147 against West Indies, earning his first Man of the Match award and on December 26, 2003, in a Test match against Australia, he scored 195. In 2004, Virender Sehwag scored the first ever triple century by an Indian with 309 runs against Pakistan, earning the Man of the Match award and later, the Man of the Series award. <br /><br />
            The same year, he scored 155 against Australia in Chennai and 164 in the first Test of the series against South Africa and 88 in the second, claiming the Man of the Series award once again. At the 2005 three-match Test series against Pakistan, Sehwag scored 544 runs at an average of 90.66, and he went on to cross 3000 runs becoming the fastest Indian to reach it in terms of innings played. <br /><br />
            For his performance in the earlier 12-month period, Sehwag got selected to the International Cricket Council (ICC) Test Team of the Year and also got nominated for the Test Player of the Year award. He captained the side in the third Test match of a series against Sri Lanka in the absence of Rahul Dravid, leading the team to victory.<br /><br />
            In January 2005, Sehwag scored 254 against Pakistan, which was the highest ever Test score at a strike rate of above 100 and the second fastest double century. In the process, he was also involved in the 410 run partnership with Rahul Dravid, which was just four short of a record opening partnership in Tests. In the second Test match of the 2006 West Indies tour, Sehwag hit 180 runs in 190 balls and also took four wickets to become the Man of the Match. In the fourth Test match of the December 2007 series against Australia, he scored a match-saving 151 in the second innings, his first century in the second innings of a test match. In the April 2008 home series against South Africa, Sehwag claimed the fastest Test triple century with 319 in the first Test in Chennai, becoming the third batsman to score 2 triple centuries.<br /><br />
            Sehwag made his One Day International debut in April 1999, but came to prominence in March 2001, when he earned a Man of the Match award for his all-round performance in a game against Australia. In August 2001, in a tri-series involving India, Sri Lanka, and New Zealand, Sehwag opened the innings for India in the absence of Sachin Tendulkar. In the finalist-decider against New Zealand, he scored his maiden ODI century in just 69 balls, the second fastest ODI century by an Indian. <br /><br />
            In 2002, he scored the second fastest half-century in just 22 balls against Kenya in Bloemfontein. In the India-England ODI Series in January 2002, Sehwag entered the pitch as an opening batsman in Sourav Ganguly's absence, and this time he sealed the opening spot for himself. In the 2002 ICC Champions Trophy in Sri Lanka, Sehwag scored 271 runs at an average of 90.33, earning two Man of the Match awards in the tournament. <br /><br />
            Sehwag and Sourav Ganguly, have two big ODI partnerships, 192 against England, in which Sehwag scored 126 from 104 balls and 196 against West Indies, in which he scored an unbeaten 114 from 82 balls. <br /><br />
            Sehwag was the only batsman to score a century in the 7 match ODI series against New Zealand, scoring two centuries, 108 in Napier and 112 in Auckland. He played in the 2003  ICC Cricket World Cup and scored his tournament highest of 82 in the final against Australia.<br /><br />
            At the 2003-04 ODI series, Sehwag scored one century and 3 fifties and in 2004 and at the 2004-05 ODI series, he earned 3 Man of the Match awards. In the 2007 ICC Cricket World Cup, he scored 114 from 87 deliveries against Bermuda in India's total score of 413, which is the highest team total in a World Cup match. <br /><br />
            For the Indian Premier League, Sehwag plays for the Delhi Daredevils and is its most expensive player with a contract worth nearly a million dollars.

<br /><br />
            </div>

		</div>
	</center>
</div>