<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Pride of the community</font>
	</div>
	<div class="linesep"><img src="images/trans.gif" height="1" width="1" /></div>
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:10px;">
			<img src="http://img.manglikmatrimony.com/images/manglik-asih.jpg" style="padding-right:12px;float:left;"/><b>9th Most Beautiful Woman in the World!</b><br><br>
			Aishwarya Rai Bachchan has often been hailed by the media as the most beautiful woman in the world and has been the most popular face of Indian cinema globally. In 2004 she was chosen by Time magazine as one of the World's "100 Most Influential People" and appeared on the cover of Time magazine, Asia Edition in 2003. In October 2004 a wax figure of Rai was put on display in London's Madame Tussaud's wax museum. She was the 6th Indian and the second Bollywood personality after her father-in-law Amitabh Bachchan to get this honour. Rai is without a doubt the most famous Manglik in India today<br><br>
			She was the subject of a 60 Minutes profile on 2 January 2005, which said that "at least according to thousands of Web sites, Internet polls and even Julia Roberts", she was "The World's Most Beautiful Woman". The same year she became a global brand ambassador of L'Oreal alongside Andie Macdowell, Eva Longoria and Penelope Cruz and a special tulip in the Netherlands was named "Aishwarya Rai" after her.<br><br>
			Aishwarya Rai was born on November 1st 1973 in Mangalore to a marine engineer Krishna Rai and a writer mom Vrinda Rai. She did her schooling in Mumbai and aspired to be an architect. She started modeling at 20 and got her first big break with Aamir Khan in the famous Pepsi commercial. She captured international attention after winning the Miss World title in 1994. <br><br>
			Rai made her movie debut in Mani Ratnam's Tamil film Iruvar (1997) and had her first commercial success in the Tamil movie Jeans (1998). She cornered the attention of Bollywood in the movie Hum Dil De Chuke Sanam (1999), directed by Sanjay Leela Bhansali. Her performance in the film won her the Filmfare Best Actress Award. In 2002 she appeared in Bhansali's next project, Devdas (2002), for which she won her second Filmfare Best Actress Award.<br><br>
			Rai has acted in nearly 50 movies in Hindi, English, Tamil and Bengali including the international productions Bride & Prejudice (2004), The Mistress of Spices (2005), The Last Legion (2007) and The Pink Panther 2 (2009) in English.<br><br>
			After a low phase in her career during 2003-2005, she appeared in the blockbuster Dhoom 2 (2006), which turned out to be her biggest Bollywood commercial success. She later appeared in films like Guru (2007) and Jodhaa Akbar (2008), which were commercially successful and gained her critical acclaim.<br><br>
			Her elder brother, Aditya Rai, is an engineer in the merchant navy and has also co-produced one of Rai's movies, Dil Ka Rishta (2003). At an early age her parents moved to Mumbai where she attended the Arya Vidya Mandir high school in Santa Cruz. Rai then entered Jai Hind College at Churchgate for one year, and then moved to Ruparel College in Matunga to finish her HSC studies. She did well in school and planned to become an architect and pursued studies in architecture. She can communicate in several languages, including her mother tongue Tulu as well as Hindi, English, Marathi and Tamil.<br><br>
			While pursuing her studies in architecture, Rai began modelling on the side. In the 1994 Miss India contest, she won the second place behind Sushmita Sen, and was crowned Miss India World. She went on to win the Miss World title the same year, where she also won the Miss Photogenic award. She abandoned her academic education after winning the pageant and spent one year reigning as Miss World in London. Rai then started working as a professional model and then moved on to her current profession as an actress.<br><br>
			In 2009 Rai was awarded the Padma Shri for her contributions to Indian cinema. In the same year she refused to accept the second-highest Order Of France, Ordre des Arts et des Lettres as her father was suffering from serious illness, and she wanted her whole family to attend the award function. She is only the fourth Indian actor after Amitabh Bachchan, Nandita Das and Shahrukh Khan to be chosen for an Order Of France. In June 2009, she was declared the Female Star of The Decade at the tenth International Indian Film Academy Awards held in Macau.<br><br>
			In 1999 Rai participated in a world tour called the Magnificent Five along with Aamir Khan, Rani Mukerji, Akshaye Khanna and Twinkle Khanna. In 2003 she became the first Indian actress to be a jury member at the Cannes Film Festival.<br><br>
			Rai is the brand ambassador for The Eye Bank Association of India's nationwide campaign to promote eye donation in India. In 2004 she travelled to Siachen Glacier to boost the morale of the jawans for a special New Year episode on the NDTV show, Jai Jawan. In 2005, she became a brand ambassador for Pulse Polio, a campaign established by the Government of India in 1994 to eradicate Polio in India.<br><br>
			In February 2005, Rai performed at the HELP! Telethon Concert to help raise money for the victims of 2004 tsunami earthquake in company with other Bollywood stars. In 2008 she along with her family laid the foundation of a special school for underprivilged girls in the Daulatpur village in Uttar Pradesh. The school will be made by her family and is going to be named after her.<br><br>
			She appeared along with various other Bollywood actors at the closing ceremony of the 2006 Commonwealth Games in Melbourne, as part of a performance showcasing Indian culture, on behalf of the 2010 Commonwealth Games. In Summer 2008, Rai joined her husband and father-in-law along with Preity Zinta and Ritesh Deshmukh on the Unforgettable World Tour. The first leg of the tour covered the USA, Canada, London, and Trinidad. <br><br>
			Rai is married to actor Abhishek Bachchan and their engagement was announced on 14 January 2007. His father Amitabh Bachchan later confirmed the announcement. The couple got married on 20 April 2007 according to traditional Hindu rites of the South Indian Bunt community, to which she belongs. Token North Indian and Bengali ceremonies were also performed. The wedding took place in a private ceremony at the Bachchan residence Prateeksha in Juhu, Mumbai. Though the wedding was a private affair intended for the Bachchan and Rai families and friends, the involvement of the media turned it into a national extravaganza. They have been cited as a supercouple in the Indian media. Rai has been very close to her family and lived with them in Bandra, Mumbai until her marriage.<br><br>
			</div>
		</div>
	</center>
</div>