<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Pride of the community</font>
	</div>
	<div class="linesep"><img src="images/trans.gif" height="1" width="1" /></div>
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:10px;">
			<b>Mohanlal: Pride of Kerala</b><br><br>
				<img src="http://img.nairmatrimony.com/images/nairmatrimony-imgm.jpg" style="padding-right:12px;float:left;"/>Mohanlal Vishwanathan Nair, better known as Mohanlal, is one of the most versatile actors of Indian cinema and an icon of Kerala.  To millions of Malayalees the world over, he is affectionately known as Lalettan.<br><br>
				Mohanlal has won four national awards, six state awards and was honoured with the Padma Sri in 2001. In 2009, the Territorial Army granted him the honorary rank of Lieutenant Colonel.<br><br>
				Mohanlal was born in Elanthur in Pathanamthitta district of Kerala. His father Vishwanathan Nair was a lawyer and government employee and mother Santhakumari was a homemaker. The family later shifted to Mudavanmugal in Thiruvananthapuram where Lal attended the Mudavanmukal LP School and the Model School, Thiruvananthapuram. An average student at school, he excelled in dramatics and won the best actor award on several occasions.<br><br>
				Lal's passion for acting continued while in college where he met a group of fellow-students who were equally passionate about theatre and feature films. The group comprised noted director Priyadarshan, playback singer M.G.Sreekumar and actor/producer Maniyanpilla Raju.<br><br>
				Lal's first film "Thiranottam" sank without a trace. But his second film, Manjil Virinja Pookkal, in 1980 where he played the role of a neurotic villain went on to become a huge hit. There was no looking back after that. In 1983, he appeared in more than 25 films including the superhit Uyarangalil directed by I. V. Sasi and Poochakkoru Mookkuthi made by his director-friend and college mate Priyadarshan.<br><br>
				The year 1986 was one of his best. Sathyan Anthikad's T.P.Balagopalan M.A got him his first Kerala state award for best actor. But it was his role of an underworld don in the blockbuster Rajavinte Makan that saw the rise of Mohanlal as the superstar of Malayalam cinema. In the same year, he played a lunatic in Thalavattom, a harassed house-owner in Sanmanassullavarku Samadhanam, a journalist in M.T.Vasudevan Nair's Panchagni, a farm owner in love in Namukku Parkkan Munthiri Thoppukal and an unemployed youth forced to become a Gurkha in Gandhi Nagar 2nd Street.<br><br>
				Other notable films during this period include the socially hard-hitting satires like Nadodikkattu, in which he played an unemployed youth and Varavelpu where he dons the role of a Gulf returnee who is welcomed back home by greedy relatives and a state with a hostile climate for entrepreneurs. He played the typical romantic hero in Priyadarshan's musical comedies like Chithram and Kilukkam that struck a chord with Kerala's youth and increased his popularity.<br><br>
				Lal's Devaasuram in 1993, directed by I.V. Sasi and written by Renjith, was a cult classic. Equally memorable films followed like Thoovanathumbikal, Amrithamgamaya and Thazhvaram.<br><br>
				His role of Sethu Madhavan, who aspires to be a police officer but ends up as a criminal in the film Kireedam, directed by Sibi Malayil, earned him a special jury award. Another role of a classical singer who has to face the jealousy and final death of his singer brother in Bharatham helped him bag the Best Actor National Award.<br><br>
				Hugely successful entertainers like His Highness Abdullah, Midhunam, Minnaram, Thenmavin kombath and Manichitrathazhu further consolidated his position in the film industry. Director Bhadran's Spadikam became another cult classic. <br><br>
				The late 1990s saw Mohanlal portraying invincible, larger-than-life characters in many films, which gained immense popularity. These included "Aaram Thamburan" and "Narasimham" (2000). A variation to the role of heroic personality was showcased in "Guru" (1997), directed by Rajiv Anchal, which was selected by the Government of India as official entry for 'Academy Award for Best Foreign Language Film'. The film "Kaalapani" (1996), directed by Priyadarshan, was critically well acclaimed as well. Mohanlal bagged his second national award for the role of a Kathakali dance artist in the film "Vaanaprastham" (1999), directed by Shaji N Karun.<br><br>
				Lal acted in his first non-Malayalam movie in director Mani Ratnam's Tamil film Iruvar where he played MGR, a cult figure in Tamil Nadu.  In 2002, Mohanlal acted in his first Bollywood movie, Company, which introduced him to the wider Hindi-speaking audience in India. It was a critical and commercial hit. He won the IIFA award, Star Screen Award for best supporting actor for this role.<br><br>
				In 2006, the film Thanmathra won him the Kerala State Award for Best Actor for portraying a person afflicted with Alzheimer's disease. His second Bollywood movie, Ram Gopal Varma Ki Aag, was the remake of the 1975 blockbuster movie Sholay, in which he played the character of the inspector played by Sanjeev Kumar in the original. 
Mohanlal won the 2007 Kerala State Award for Best Actor for his performance as Valiakathu Moosa in the movie Paradesi. In 2009, Mohanlal acted with Kamal Hassan in a Tamil movie called Unnaipol Oruvan. <br><br>
Mohanlal is an art lover and has a deep interest in various art forms. He is a passionate collector of paintings and antiques. The actor has built a private art gallery at his home. He is married to Suchitra, daughter of veteran Tamil actor-producer K. Balaji. The couple has two children - Pranav and Vismaya.<br><br>
			</div>
		</div>
	</center>
</div>