<div class="rpanel fleft">
	<div class="normtxt1 clr2 padb5">
		<font class="clr bld">Wedding customs</font>
	</div>
	<div class="linesep"><img src="images/trans.gif" height="1" width="1" /></div>
	<center>
		<div class="rpanelinner padt10">
			<div class="normtxt clr lh16 tljust" style="padding-top:10px;">
            Niyogin in Sanskrit means, "employed" or "appointed" or "assigned" and it is quite probable that Niyogis were given this name because they accepted secular employment assigned to them.<br /><br />
            Niyogis are a sect of Brahmins who gave up religious or priestly occupations and are predominantly Telugu-language speakers.<br /><br />
            <b>Marriage Rituals</b><br />
            <b>The Nischaiyathartham or engagement ceremony:</b> The engagement function mainly involves the drawing up of the "lagna patrika" or a paper specifiying the date, time and venue of the marriage. In the case of Iyers, the ceremony is held in the groom's residence but it is just the opposite with the Iyengars. Dinner and sweets are served by whoever is hosting the ceremony but the groom's family gifts a sari to the bride.   <br /><br />
            <b>Pandakol:</b> The wedding celebrations commence a day before the wedding when the bride's family start decorating and purifying the mandap in which the rites are to be performed. Milk, saffron and kumkum are poured on the bottom of the bamboo poles placed at the four corners of the mandap. <br /><br />
            <b>Vratham or anointing the bride and groom:</b> This is a ceremony to obtain the blessings from the departed elders of both families. A sacred yellow thread is tied on the wrists of the bride and groom and nine varieties of grains are sprinkled for the prosperity of the couple's new life together. These rituals are observed separately for the bride and groom. The function rounds off with an arthi.  <br /><br />
            <b>Wedding preparations:</b> The bride's family sends toiletries, a mirror, a basket filled with sweetmeats and a 'nadeshwaram' to the groom's family. The groom's aunt brings a dish of 'appams' (pancakes made from rice flour and jaggery) for this occasion, while the 'pujaris' usually tie the traditional 'dhoti' or 'panchakatcham' for the groom and apply 'vibhuti' or sacred ash in three horizontal lines on his forehead.<br /><br />
            <b>Janavasam & Nischaiyartham:</b> This ritual held in a temple is a significant part of the marriage ceremonies as it provides an opportunity to the families to sort out any differences between them. The bride's family brings turmeric, betel leaves, nuts and clothes and garlands the groom even as sugar candy is distributed to all present. The groom is then escorted to a decorated car and the family leaves in a procession for the 'mandapam'. <br /><br />
            Once the procession reaches the marriage venue, the bride is led outside by her close friends to get a glimpse of her future husband! An arthi is performed and a coconut broken to ward off evil. When the groom arrives at the venue, the bride's family welcome him with sandalwood paste, kumkum, rose water, sugar candy, garlands and perform an arthi. He is also given 'thiraattupal' (condensed and sweetened milk) even as the 'nadeshwaram' (traditional wind instrument) is played in his honour.<br />
            The groom is then led to mandap and the members of both families sit opposite each other and a 'lagna patrika' (marriage contract) is written and read aloud by the 'pujari'. 'Thamboolams' (platters of betel nuts, dry fruits, nuts, coconuts, turmeric and 'kumkum') and gifts are exchanged. <br /><br />
            <b>Kashi Yatra:</b> Dressed in the traditional 'panchakatcham', holding an umbrella, a fan, a walking stick, and a towel containing 'dal' (lentils) and rice tied to his shoulder, the groom embarks on a mock pilgrimage. As he steps out of the 'mandapam', the bride's father pleads with him not to go off on a  Kashi pilgrimage and marry his daughter instead. After much ado the groom accepts and returns to the 'mandappam' to get married!<br /><br />
            <b>The Unjal:</b> The couple exchange garlands here and they are made to sit on a swing and the womenfolk smear their feet with milk, kumkum and sandalwood paste. This is to protect them from the evil eye.<br /><br />
            <b>Kanyadhan:</b> The bride is given away in this ceremony. Amid the chanting of Vedic mantras, the pujari ignites the sacred fire. The groom is gifted a 'muhurtha veshti' (a four metre long silk dhoti) and a pattu (a 2 metre long silk fabric to be used as a stole). The bride is seated on her father's lap during the 'kanyadhan'. The bride and groom then together hold a coconut dipped in turmeric, while the bride's mother pours water onto the coconut.<br /><br />
            <b>Mangalyadharanam:</b> The groom ties the sacred taali on the bride. In this ceremony the taali is placed on the bride's head along with a miniature piece of jewellery shaped like a yoke and the groom performs a puja with kumkum and flowers. He then ties the first knot of the taali around the bride's neck and his sister ties the other two.  <br /><br />
            <b>Sapthapathi:</b> Seven steps around the sacred fire: The bride's sari 'pallav' and the groom's 'angavastram' (shawl) are tied in a knot and the couples hold hands. The groom places his foot under the bride's and helps her to take the seven steps around the fire. Then he places the bride's foot on a grinding stone near the fire and slips silver rings or 'metti' on her toes. The couple is then shown the 'Dhruva Nakshatra' or the Pole Star, a symbol of permanence and the 'Arundhati Nakshatra' or symbol of purity and virtue.<br /><br />
            <b>Laja Homam:</b> The bride's brother slings a bagful of puffed rice or 'laja' over his shoulder and gives fistfuls of the rice periodically to his sister who in turn offers it as a sacrifice to the sacred fire. After this ritual, the couple is blessed by the people. <br /><br />
            <b>Sesha Homam:</b> This is a symbolic ritual to invoke the blessings for healthy offspring with the groom tying a thread around the bride's hip.<br /><br />
            <b>Gruhapravesam:</b> If the grooms' family lives in the same town, the bride is taken to her new home and made to sit on a 'manai' (low wooden plank) and fed milk and bananas. Her in-laws gift her with a sari and she is asked to light the sacred lamp in the puja room. If the groom's family does not live in the same town, this ceremony is performed in the 'mandapam' after completing the marriage rites.<br /><br />
            <b>Seer Bakshanam:</b> The bride's parents prepare several sweets and savouries for the bride to take back with her to her husband's home. These are known as 'seer bakshanam' and are stored in decorated containers and later distributed amongst friends and relatives by the groom's family.<br /><br />

            </div>
		</div>
	</center>
</div>